version: '3'
services:
  ranger-build:
    build:
      context: .
      dockerfile: Dockerfile.ranger-build
    image: ranger-build
    container_name: ranger-build
    hostname: ranger-build.example.com
    networks:
      - ranger
    volumes:
      - ~/.m2:/home/ranger/.m2
      - ./dist:/home/ranger/dist
    depends_on:
      - ranger-base
    environment:
      BRANCH: 'ranger-2.1'
      SKIPTESTS: 'true'

networks:
  ranger:
