version: '3'
services:
  ranger-hbase:
    build:
      context: .
      dockerfile: Dockerfile.ranger-hbase
    image: ranger-hbase
    container_name: ranger-hbase
    hostname: ranger-hbase.example.com
    stdin_open: true
    tty: true
    networks:
      - ranger
    ports:
      - "2181:16181"
      - "16010:16010"
      - "16020:16020"
    depends_on:
      - ranger-hadoop

networks:
  ranger:
