version: '3'
services:
  ranger-hadoop:
    build:
      context: .
      dockerfile: Dockerfile.ranger-hadoop
    image: ranger-hadoop
    container_name: ranger-hadoop
    hostname: ranger-hadoop.example.com
    stdin_open: true
    tty: true
    networks:
      - ranger
    ports:
      - "9000:9000"
      - "8088:8088"
    depends_on:
      - ranger

networks:
  ranger:
